spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: never

